name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.1

      - name: Install dependencies
        run: uv sync --group docs

      - name: Deploy docs
        run: uv run mkdocs gh-deploy --force
